### ISSUE TITLE
Is there a way to see/copy trade totals?

### ISSUE THREAD

**Issue by dylan-k** [anthonylangsworth/EDMFAT#1]
It's good to see the total amounts of materials traded and the average credits per ton, but in some squadrons we talk about trade totals. Is it possible to see or copy that information from EDMFAT, or could it be? Currently I use an app called First Contact for that, but having it in EDMC with everything else would be great.

**Comment by anthonylangsworth** [comment]
Forgive my ignorance but what do you mean by a "trade total"? I am happy to make useful changes but what, specifically, do you want to see?

**Comment by dylan-k** [comment]
Sorry I guess that wasn't too clear. What I mean is to see a total number of credits spent or earned.

**Comment by anthonylangsworth** [comment]
Thanks for the clarification. That information is captured by the EDMFAT plug-in today. Changing it to total tonnage is a relatively simple change.

However, may I ask why you report BGS trade using trade totals? I report the average profit per tonne (or ton) because this is BGS relevant (influence maxes out at about 700 CR per tonne) and total tonnage (to estimate the total work whether it was multiple smaller trips or fewer larger ones).

**Comment by dylan-k** [comment]
In the Discord for the Elite Dangerous Order of Mobius player faction, we post information about credits earned for each run. I don't know why, to be honest. I can ask though. I'll share what I find out.

**Comment by anthonylangsworth** [comment]
Thanks, @dylan-k ! I am also happy to join your Discord as a guest if that would help, too.

**Comment by anthonylangsworth** [comment]
@dylan-k Did you make any progress on this? Can I assist?

**Comment by dylan-k** [comment]
Here's a link to the discord. If you look for the channels with stars in
their names you'll usually see where the reports are. There can be reports
of influence from missions, or credits from trading, etc.
https://discord.gg/aGux6pdn

**Comment by anthonylangsworth** [comment]
@dylan-k I know it has been a while but this will be addressed in #6.  I am happy to explain further if needed.

**Comment by dylan-k** [comment]
nice! Thanks for the update :)

**Comment by anthonylangsworth** [comment]
Thanks for your patience.

**Comment by anthonylangsworth** [comment]
Fix in release v0.28. Closing.
